- name: Run script on EC2
  hosts: ec2
  tasks:
    - name: Upload script
      copy:
        src: files/script.sh
        dest: /tmp/script.sh
        mode: '0755'

    - name: Execute script
      command: /tmp/script.sh
