- name: Configure EC2 instance
  hosts: ec2
  become: yes
  tasks:

    - name: Upload script
      copy:
        src: files/script.sh
        dest: /home/ec2-user/script.sh
        mode: '0755'

    - name: Execute script
      command: /home/ec2-user/script.sh

    - name: Install Nginx (AL2 and AL2023 compatible)
      shell: |
        (dnf install -y nginx || amazon-linux-extras enable nginx1 && yum clean metadata && yum install -y nginx)
      args:
        executable: /bin/bash

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
