- name: Configure EC2 instance
  hosts: ec2
  become: yes
  tasks:

    - name: Install Nginx
      shell: |
        (dnf install -y nginx || amazon-linux-extras enable nginx1 && yum clean metadata && yum install -y nginx)
      args:
        executable: /bin/bash

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom HTML
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: Copy mission photo
      copy:
        src: mission.jpg
        dest: /usr/share/nginx/html/mission.jpg
        mode: '0644'
